GamingQueue.new(user_id:8, game_id:7).save
GamingQueue.new(user_id:9, game_id:7).save
GamingQueue.new(user_id:9, game_id:8).save
GamingQueue.new(user_id:7, game_id:9).save
GamingQueue.new(user_id:7, game_id:14).save
GamingQueue.new(user_id:6, game_id:13).save
GamingQueue.new(user_id:6, game_id:12).save
GamingQueue.new(user_id:11, game_id:12).save
GamingQueue.new(user_id:7, game_id:8).save
GamingQueue.new(user_id:13, game_id:9).save
GamingQueue.new(user_id:13, game_id:11).save
GamingQueue.new(user_id:13, game_id:16).save
GamingQueue.new(user_id:6, game_id:10).save
GamingQueue.new(user_id:6, game_id:14).save
GamingQueue.new(user_id:12, game_id:13).save
GamingQueue.new(user_id:12, game_id:12).save
GamingQueue.new(user_id:14, game_id:13).save
GamingQueue.new(user_id:14, game_id:6).save
GamingQueue.new(user_id:15, game_id:7).save
GamingQueue.new(user_id:15, game_id:8).save
GamingQueue.new(user_id:16, game_id:9).save
GamingQueue.new(user_id:16, game_id:11).save
