Game.create(name: "Settlers of Catan", min: 3, max: 4, quick_description: "A small empire buildiong game.\nRoll dice to get resources, trade resources with other players.",user_id:1)
Game.create(name: "Dominion", min: 2, max: 4, quick_description: "A deck building game.\nYou must collect cards from the library.  Every time you play, it's different!",user_id:1)
Game.create(name:"Small World", min: 2, max: 5, quick_description: "Zany fantasy strategy game.\nUse troops to occupy territory and occupy nearby lands.",user_id:1)
Game.create(name:"Jenga", min: 2, max: 4, quick_description: "It's Jenga. Haven't you played Jenga?",user_id:1)
Game.create(name:"Pandemic: Legacy", min: 2, max: 4, quick_description: "You and the other players must\nsave the world from deadly diseases.",user_id:1)
Game.create(name:"Magic: The Gathering", min: 2, max: 2, quick_description:"Dual an opponent in this fantasy based,\nstrategic card game. Rules not included.",user_id:1)
Game.create(name:"7 Wonders", min: 3, max: 7, quick_description:"A empire building game with cards.\nAll players use the same cards to strategically build.  Says it can be two. Don't play with two.",user_id:1)
Game.create(name:"Monopoly", min: 2, max: 5, quick_description:"Don't. Just... don't. May the RNG gods be with you.",user_id:1)
Game.create(name:"Set", min: 2, max: 4, quick_description:"Unique cards are laid face up on the table,\neach player must as quickly as they can find three that form a 'set'.\nGreat for pattern recognition.",user_id:1)
Game.create(name:"Bananagrams", min: 2, max: 4, quick_description:"Kinda like scrabble but without the board.",user_id:1)
Game.create(name:"Cranium", min: 4, max: 8, quick_description:"Trivial Pursuit meets charades and art.  Entertaining with the free beer they offer here.",user_id:1)
Game.create(name:"Dungeons & Dragons", min: 4, max: 6, quick_description:"We're all nerds here. Just ask anyone.",user_id:1)
